export default function Recommendations() {
  return (
    <div className="p-6">
      <h2 className="text-base font-semibold text-zinc-800 dark:text-zinc-100 mb-1">
        AI Recommendations
      </h2>
      <p className="text-sm text-zinc-400 dark:text-zinc-500 mb-6">
        5 stocks to consider buying next, generated by GPT-4o based on your portfolio and market
        context. Each pick comes with plain-English reasoning.
      </p>

      <div className="rounded-lg border border-dashed border-zinc-200 dark:border-zinc-700 p-8 text-center">
        <p className="text-sm text-zinc-400 dark:text-zinc-500">No recommendations yet.</p>
        <p className="text-xs text-zinc-300 dark:text-zinc-600 mt-1">Coming in v1.1.0.</p>
      </div>
    </div>
  )
}
